name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tags
        id: determine_tags
        run: |
          BASE_IMAGE="ghcr.io/jonded94/relax-check-rs"
          BRANCH_NAME="${GITHUB_REF_NAME}"
          TAGS="${BASE_IMAGE}:$BRANCH_NAME"
          if [ "${BRANCH_NAME}" == "main" ]; then
            TAGS="${TAGS},${BASE_IMAGE}:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.determine_tags.outputs.tags }}
